### ISSUE TITLE
Page blanche

### ISSUE THREAD

**Issue by adrien80080** [YunoHost-Apps/kiwiirc_ynh#1]
Bonjour !
j'ai installé Kiwi IRC à la racine du domaine (ex : irc.domain.tld)
Mais j'ai une zolie page blanche.

Je ne sais pas d'ou ca peut venir, une idée ?

**Comment by julienmalik** [comment]
Hey ! Does this mean it now works ?

**Comment by adrien80080** [comment]
hello,
yes, this problem is caused by NodeJS in RPi.
I have write a solution here : https://abhd.fr/pad/p/r.716555d1ac33d95c0a65e4c1a033d791
