### ISSUE TITLE
config.json has bad group post install

### ISSUE THREAD

**Issue by theabhinavdas** [YunoHost-Apps/kiwiirc_ynh#6]
The file in question is:

`/var/www/kiwiirc/static/config.json`

`ls -al` shows:

`-rw-r-----  1 kiwiirc root 1043 Nov  9 20:19 config.json`

Which should be `-rw-r-----  1 kiwiirc www-data 1043 Nov  9 20:19 config.json`

**Comment by ghost** [comment]
Any update on this?

**Comment by ericgaspar** [comment]
Fixed in master
