### ISSUE TITLE
Binary is for x86 

### ISSUE THREAD

**Issue by navanchauhan** [YunoHost-Apps/kiwiirc_ynh#7]
### Describe the bug

[The binary used to install kiwi irc is an x86 binary](https://github.com/YunoHost-Apps/kiwiirc_ynh/blob/6bf340aef64286cbe8792804710c9978e117110f/sources/webircgateway/kiwiirc)

### Expected behavior

Sources file should be updated to handle all three different architectures x86, armhf and arm64

If I get time over the weekend I will try creating a test branch and bumping the version to 1.6

Edit:

```
/Users/navanchauhan/Downloads/kiwiirc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=QdKksvY8W_mKhulaxXVG/YfweN_IMG87QnFHsyFqB/zwGvdTjCaSwgIptZ56VP/qIYQGdxp_Sn4iALZeBGY, BuildID[sha1]=7551042e2affe98636b76999062113d90e88b02a, not stripped
```

**Comment by Salamandar** [comment]
It should be fixed with the next version.
